train:
  batch_size: 512
  num_epochs: 10
  learning_rate: 0.001
  optimizer: "adam"
  device: "mps" 
  grad_clip: 0
  grad_accum_steps: 1
  do_validation: true

model:
  num_classes: 10

logging:
  print_every: 1 
  save_model: true
  model_save_path: "./trained/hindi.pth"