train:
  batch_size: 128
  num_epochs: 5
  learning_rate: 0.001
  optimizer: "adam"
  device: "mps" 
  grad_clip: 0
  grad_accum_steps: 1
  do_validation: true

model:
  num_classes: 10  # 10 classes for MNIST

logging:
  print_every: 1 
  save_model: true
  model_save_path: "./trained/mnist.pth"